import type { Metadata } from "next";
import { Irish_Grover } from "next/font/google";
import "./globals.css";

import { AuthProvider } from "@/context/auth";

const irishGrover = Irish_Grover({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-irish-grover",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${irishGrover.variable}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
